[package]
name = "testdrive"
description = "Integration test driver for Materialize."
version = "0.1.0"
authors = ["Nikhil Benesch <nikhil.benesch@gmail.com>"]
edition = "2018"

[[bin]]
name = "testdrive"
path = "main.rs"

[dependencies]
atty = "0.2"
failure = "0.1.5"
ore = { path = "../ore" }
postgres = "0.16.0-rc.1"  # pre-release for simple_query support
sqlparser = { git = "ssh://git@github.com/MaterializeInc/sqlparser.git" }
rdkafka = "0.20"
reqwest = "0.9.15"
termcolor = "1.0.4"

[dev-dependencies]
assert_cmd = "0.11.1"
predicates = "1.0.0"
