[package]
name = "ore"
description = "Internal utility libraries for Materialize."
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
env_logger = "0.7.1"
failure = "0.1.6"
fallible-iterator = "0.2.0"
futures = "0.3"
lazy_static = "1.4.0"
libc = "0.2.66"
log = "0.4.8"
tokio = { version = "0.2", features = ["io-util", "rt-threaded", "tcp"] }
smallvec = "1.1"

[dev-dependencies]
crossbeam = "0.7.2"
