[package]
name = "ore"
description = "Internal utility libraries for Materialize."
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
env_logger = "0.7.0"
failure = "0.1.5"
fallible-iterator = "0.2.0"
futures = "0.1"
lazy_static = "1.4.0"
libc = "0.2.62"
log = "0.4"
slog = { version = "2.5.2", features = ["max_level_trace"] }
tokio = "0.1"
smallvec = "0.6"

[dev-dependencies]
crossbeam = "0.7.2"
