[package]
name = "ore"
description = "Internal utility libraries for Materialize."
version = "0.1.0"
authors = ["Nikhil Benesch <nikhil.benesch@gmail.com>"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
env_logger = "0.6.1"
futures = "0.1"
lazy_static = "1.3.0"
log = "0.4"
slog = { version = "2.4.1", features = ["max_level_trace"] }
tokio = "0.1"
smallvec = "0.6"

[dev-dependencies]
crossbeam = "0.7.1"