[workspace]
members = [
    "src/metastore",
    "src/materialize",
    "src/ore",
    "src/testdrive",
]

# TODO(benesch): remove this when rdkafka is updated upstream.
[patch."https://github.com/benesch/timely-dataflow.git"]
timely = { git = "https://github.com/TimelyDataflow/timely-dataflow.git" }

[patch.crates-io]
rdkafka = { git = "ssh://git@github.com/MaterializeInc/rust-rdkafka.git" }
