[workspace]
members = [
    "fuzz",
    "src/ccsr",
    "src/metastore",
    "src/materialize",
    "src/ore",
    "src/testdrive",
    "src/sqllogictest",
]

[profile.release]
debug = true

[patch.crates-io]
# TODO(benesch): remove rdkafka patch when 0.22 is released.
rdkafka = { git = "ssh://git@github.com/fede1024/rust-rdkafka.git" }
avro-rs = { git = "ssh://git@github.com/MaterializeInc/avro-rs.git" }
futures = { git = "ssh://git@github.com/MaterializeInc/futures-rs.git", branch = "0.1" }
