[workspace]
members = [
    "src/metastore",
    "src/materialize",
    "src/ore",
    "src/testdrive",
    "src/sqllogictest",
]

[profile.release]
debug = true

# TODO(benesch): remove when https://github.com/fede1024/rust-rdkafka/pull/117
# lands.
[patch.crates-io]
rdkafka = { git = "ssh://git@github.com/MaterializeInc/rust-rdkafka.git" }
futures = { git = "ssh://git@github.com/MaterializeInc/futures-rs.git", branch = "0.1" }