[workspace]
members = [
    "src/metastore",
    "src/materialize",
    "src/ore",
    "src/testdrive",
]

# TODO(benesch): remove when https://github.com/fede1024/rust-rdkafka/pull/117
# lands.
[patch.crates-io]
rdkafka = { git = "ssh://git@github.com/MaterializeInc/rust-rdkafka.git" }
