[package]
name = "avro-rs"
version = "0.6.5"
authors = ["Flavien Raynaud <flavien.raynaud@gmail.com>", "Antonio Verardi <antonio.uccio.verardi@gmail.com>"]
description = "Library for working with Apache Avro in Rust"
license = "MIT"
readme = "README.md"
repository = "https://github.com/MaterializeInc/avro-rs"
edition = "2018"

[features]
snappy = ["byteorder", "crc", "snap"]

[dependencies]
byteorder = { version = "1.0.0", optional = true }
crc = { version = "1.3.0", optional = true }
chrono = { version = "0.4" }
digest = "0.8"
failure = "0.1.5"
futures = "0.3"
libflate = "0.1"
log = "0.4.8"
rand = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snap = { version = "0.2.3", optional = true }
tokio = { version = "0.2", features = ["io-util", "rt-threaded", "macros"] }

[dev-dependencies]
md-5 = "0.8"
lazy_static = "^1.1"
sha2 = "0.8"
