[workspace]
members = [
    "fuzz",
    "src/ccsr",
    "src/comm",
    "src/dataflow",
    "src/dataflow-bin",
    "src/dataflow-types",
    "src/expr",
    "src/interchange",
    "src/peeker",
    "src/materialized",
    "src/ore",
    "src/repr",
    "src/sql",
    "src/symbiosis",
    "src/testdrive",
    "src/sqllogictest",
]

[profile.release]
debug = true
