[bans]
multiple-versions = "deny"
skip = [
    # Do not add to this list without good reason! Duplicate dependencies slow
    # down compilation and bloat the binary.

    # Awaiting https://github.com/bheisler/criterion.rs/pull/398.
    { name = "itertools", version = "0.8.0" },

    # Awaiting:
    #   - reqwest 0.13.5 (https://github.com/seanmonstar/reqwest/releases)
    #   - redox-users (https://gitlab.redox-os.org/redox-os/users/-/merge_requests/34)
    { name = "base64", version = "0.11.0" },

    # Waiting on mio 0.7: https://github.com/tokio-rs/tokio/issues/1190.
    { name = "miow", version = "0.2.1" },
    { name = "winapi", version = "0.2.8" },

    # Waiting on chrono, hyper, reqwest, and rusqlite to migrate to time v0.2.
    # time v0.2 is a total rewrite of time v0.1, so this doesn't seem likely
    # to happen any time soon.
    { name = "time", version = "0.1.42" },
]

[licenses]
allow = [
    "Apache-2.0",
    "CC0-1.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "Zlib",
]
private = { ignore = true }

[sources]
unknown-git = "deny"
unknown-registry = "deny"
allow-git = [
    "https://github.com/MaterializeInc/rust-prometheus.git",
    "https://github.com/MaterializeInc/serde-protobuf.git",
    "https://github.com/TimelyDataflow/timely-dataflow",
    "https://github.com/TimelyDataflow/differential-dataflow.git",
    "https://github.com/fede1024/rust-rdkafka.git",
    "https://github.com/sfackler/rust-postgres.git",
]
