[build]
publish = "ci/www/public"
command = "hugo --gc --baseURL $URL/docs --source doc/user --destination ../../ci/www/public/docs"
ignore = "ci/www/changed.sh"
environment = { HUGO_VERSION = "0.68.3" }

[context.deploy-preview]
publish = "doc/user/public"
command = "cd doc/user && hugo --gc --baseURL $DEPLOY_PRIME_URL"
environment = { HUGO_VERSION = "0.68.3" }

[context.branch-deploy]
publish = "doc/user/public"
command = "cd doc/user && hugo --gc --baseURL $DEPLOY_PRIME_URL"
environment = { HUGO_VERSION = "0.68.3" }
