[build]
base = "www"
publish = "public"
command = "hugo --gc --baseURL $URL"

[context.deploy-preview]
command = "hugo --gc --baseURL $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --baseURL $DEPLOY_PRIME_URL"
