[package]
name = "comm"
description = "Async-aware communication fabric that abstracts over thread/process boundaries."
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
bincode = "1.1"
futures = "0.1"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
tokio = "0.1"
tokio-serde-bincode = "0.2"
uuid = { version = "0.7.4", features = ["serde", "v4", "u128"] }
ore = { path = "../ore" }

[dev-dependencies]
assert_cmd = "0.11"
getopts = "0.2"
predicates = "1.0.1"
