[package]
name = "mz-protoc"
description = "A pure Rust protobuf compiler."
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "protoc"
path = "bin/protoc.rs"

[dependencies]
anyhow = "1.0.52"
clap = { version = "3.0.10", features = ["derive"] }
ore = { path = "../ore" }
prost-build = { git = "https://github.com/MaterializeInc/prost.git" }
tempfile = "3.2.0"
