[package]
name = "protoc"
description = "A pure Rust protobuf compiler."
version = "0.1.0"
edition = "2018"
publish = false

[lib]

[[bin]]
name = "protoc"
path = "bin/protoc.rs"

[dependencies]
anyhow = "1.0.28"
getopts = "0.2"
protobuf = { git = "https://github.com/stepancheg/rust-protobuf.git", branch = "v2.17" }
protobuf-codegen = { git = "https://github.com/stepancheg/rust-protobuf.git", branch = "v2.17" }
protobuf-codegen-pure = { git = "https://github.com/stepancheg/rust-protobuf.git", branch = "v2.17" }
tempfile = "3.1.0"
