[package]
name = "build-info"
description = "Metadata about a Materialize build."
version = "0.0.0"
edition = "2018"
publish = false

[features]
default = ["semver"]

[dependencies]
semver = { version = "0.11.0", optional = true }
