[package]
name = "persist"
description = "Abstraction for Materialize dataplane persistence."
version = "0.0.0"
edition = "2018"
publish = false

# NB: This is meant to be a strong, independent abstraction boundary, please
# don't leak in deps on other Materialize packages.
[dependencies]
timely = { git = "https://github.com/TimelyDataflow/timely-dataflow", default-features = false, features = ["bincode"] }
tempfile = "3.2.0"
