[package]
name = "pgrepr"
description = "Representation of and serialization for PostgreSQL data types."
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
byteorder = "1.3"
bytes = "0.5"
chrono = "0.4"
lazy_static = "1.4.0"
postgres-types = { version = "0.1.1", features = ["with-chrono-0_4"] }
ore = { path = "../ore" }
repr = { path = "../repr" }
