[package]
name = "materialize"
description = "Streaming SQL materialized views."
version = "0.1.0"
authors = ["Nikhil Benesch <nikhil.benesch@gmail.com>"]
edition = "2018"

[[bin]]
name = "materialized"
path = "bin/materialized.rs"

[lib]
path = "lib.rs"

[dependencies]
avro-rs = "0.6.5"
backtrace = "0.3.14"
bincode = "1.1.2"
bytes = "0.4"
byteorder = "1.3"
cast = "0.2"
differential-dataflow = { git = "https://github.com/TimelyDataflow/differential-dataflow.git" }
failure = "0.1.5"
futures = "0.1"
getopts = "0.2"
hyper = "0.12"
lazy_static = "1.3.0"
log = "0.4"
metastore = { path = "../metastore" }
ordered-float = { version = "1.0.2", features = ["serde"] }
ore = { path = "../ore" }
reqwest = "0.9.12"
rdkafka = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0.39"
simplelog = "0.5"
smallvec = "0.6"
sqlparser = { git = "ssh://git@github.com/MaterializeInc/sqlparser.git" }
state_machine_future = { git = "https://github.com/benesch/state_machine_future.git", branch = "context-generic-bounds" }
timely = { git = "https://github.com/TimelyDataflow/timely-dataflow.git", features = ["bincode"] }
tokio = "0.1"
tokio-threadpool = "0.1"
url = "1.7.2"
uuid = { version = "0.7.2", features = ["serde", "v4"] }

[dev-dependencies]
pretty_assertions = "0.6.1"
