[package]
name = "materialize"
version = "0.1.0"
authors = ["Nikhil Benesch <nikhil.benesch@gmail.com>"]
edition = "2018"

[[bin]]
name = "materialized"
path = "bin/materialized.rs"

[lib]
path = "lib.rs"

[dependencies]
bytes = "0.4"
byteorder = "1.3"
cast = "0.2"
differential-dataflow = "0.8"
failure = "0.1.5"
futures = "0.1"
hyper = "0.12"
lazy_static = "1.3.0"
log = "0.4"
ore = { path = "../ore" }
rdkafka = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0.39"
simplelog = "0.5"
smallvec = "0.6"
sqlparser = { git = "ssh://git@github.com/timelydata/sqlparser.git" }
state_machine_future = "0.2"
timely = { version = "0.8", features = ["bincode"] }
tokio = "0.1"
tokio-threadpool = "0.1"

[dev-dependencies]
pretty_assertions = "0.6.1"