baseURL = "https://materialize.io/"
languageCode = "en-us"
title = "Materialize Documentation"
pygmentsCodeFences = true
pygmentsStyle = "xcode"

[menu]
    [[menu.main]]
    identifier = "overview"
    name = "Overview"
    weight = 1

    [[menu.main]]
    identifier = "sql"
    name = "SQL"
    weight = 2
