baseURL = "https://materialize.io/"
languageCode = "en-us"
title = "Materialize Documentation"
pygmentsCodeFences = true
pygmentsStyle = "xcode"
disableKinds = ["home"]

[menu]
    [[menu.main]]
    identifier = "overview"
    name = "Overview"
    weight = 5

    [[menu.main]]
    identifier = "connections"
    name = "Connect"
    weight = 10

    [[menu.main]]
    identifier = "sql"
    name = "SQL"
    weight = 20

    [[menu.main]]
    identifier = "sql-types"
    name = "Data Types"
    url = "/docs/sql/types/"
    weight = 1
    parent = "sql"

    [[menu.main]]
    identifier = "sql-functions"
    name = "Functions + Operators"
    url = "/docs/sql/functions/"
    weight = 2
    parent = "sql"

    [[menu.main]]
    identifier = "demos"
    name = "Demos"
    weight = 30

[markup.goldmark.renderer]
# allow <a name="link-target">, the old syntax no longer works
unsafe = true
