baseURL = "https://materialize.io/"
languageCode = "en-us"
title = "Materialize Documentation"
pygmentsCodeFences = true
pygmentsStyle = "xcode"

[menu]
    [[menu.main]]
    identifier = "overview"
    name = "Overview"
    weight = 1

    [[menu.main]]
    identifier = "sql"
    name = "SQL"
    weight = 2

    [[menu.main]]
    identifier = "sql-types"
    name = "Data Types"
    url = "/docs/sql/types/"
    weight = 1
    parent = "sql"

    [[menu.main]]
    identifier = "sql-functions"
    name = "Functions + Operators"
    url = "/docs/sql/functions/"
    weight = 2
    parent = "sql"
