[package]
name = "sqllogictest"
description = "SQL correctness tests."
version = "0.0.1"
edition = "2018"

[[bin]]
name = "sqllogictest"
path = "main.rs"

[lib]
path = "lib.rs"

[dependencies]
itertools = "0.8.0"
sqlparser = { git = "ssh://git@github.com/MaterializeInc/sqlparser.git" }
materialize = { path = "../materialize" }
ore = { path = "../ore" }
getopts = "0.2"
walkdir = "2"
regex = "1"
lazy_static = "1"
failure = "0.1.5"
futures = "0.1"
uuid = "*"
md5 = "*"
