[package]
name = "aws-util"
description = "Internal AWS utility library for Materialize."
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0.37"
log = "0.4.0"
rusoto_core = { git = "https://github.com/rusoto/rusoto.git" }
rusoto_credential = { git = "https://github.com/rusoto/rusoto.git" }
rusoto_kinesis = { git = "https://github.com/rusoto/rusoto.git" }
rusoto_sts = { git = "https://github.com/rusoto/rusoto.git" }
tokio = "1.0.0"
