# Copyright 2019 Materialize, Inc. All rights reserved.
#
# This file is part of Materialize. Materialize may not be used or
# distributed without the express permission of Materialize, Inc.

steps:
  - block: ":vertical_traffic_light: Go"
  - command: ci/slt/slt.sh
    timeout_in_minutes: 120
    artifact_paths:
    - target/slt.log
    - target/slt-summary.json
    plugins:
      - docker#v3.1.0:
          image: materialize/ci-sqllogictest:$SQLLOGICTEST_IMAGE_ID
          propagate-uid-gid: true
          environment:
          - BUILDKITE
          shell: false
  - wait
  - command: ci/slt/upload.sh
    timeout_in_minutes: 10
    plugins:
      - docker#v3.1.0:
          image: materialize/ci-builder:stable-20190730-071508
          propagate-uid-gid: true
          mount-ssh-agent: true
          environment:
          - BUILDKITE_BRANCH
          - BUILDKITE_COMMIT
