# Copyright 2020 Materialize, Inc. All rights reserved.
#
# This file is part of Materialize. Materialize may not be used or
# distributed without the express permission of Materialize, Inc.


# Map from host-port:internal port
#
# This mostly just shows all the ports that are available to the host system, if you want
# to change these you must restart the docker-compose cluster.
x-port-mappings:
  - &server 5000:5000
  - &materialized 6875:6875

version: '3.7'
services:
  materialized:
    image: materialize/materialized:latest
    ports:
      - *materialized
    init: true
    command: -w4
    volumes:
      - logfile:/log

  server:
    init: true
    image: materialize/http-demo:2020-02-05
    ports:
      - *server
    volumes:
      - logfile:/log
    command: /bin/sh -c "./server.py 2> /log/requests"

  client:
    image: materialize/http-demo:2020-02-05
    init: true
    depends_on: [server]
    command: ./loadgen.py

  cli:
    image: materialize/cli
    init: true
    # if you run the terminal with a dark background uncomment these lines
    # environment:
    #   MZCLI_PROMPT: DARK_MODE
    depends_on:
      - materialized

  setup:
    image: materialize/cli
    depends_on:
      - materialized
    volumes:
      - .:/mounted
    command: /mounted/setup.sh
volumes:
  logfile:
