[package]
name = "peeker"
description = "Run peek against materialized, reporting metrics"
version = "0.1.0"
edition = "2018"
publish = false

[[bin]]
name = "peeker"
path = "peeker.rs"

[dependencies]
getopts = "0.2"
failure = "0.1.6"
regex = "1.3.1"
prometheus = { version = "0.7", features = ["push", "process"] }
chrono = "0.4.10"
postgres = { version = "0.15", features = ["with-chrono"] }
log = "0.4.10"
env_logger = "0.7.1"
