[package]
name = "transform"
description = "Transformations of Materialize expressions."
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
dataflow-types = { path = "../dataflow-types" }
expr = { path = "../expr" }
repr = { path = "../repr" }
