[package]
name = "json-flattened-view-gen"
version = "0.1.0"
edition = "2018"
authors = ["Materialize, Inc."]
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
serde_json = "1"
structopt = "0.3"
thiserror = "1"
