# Copyright Materialize, Inc. All rights reserved.
#
# Use of this software is governed by the Business Source License
# included in the LICENSE file at the root of this repository.
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0.

steps:
  - command: bin/ci-builder run stable ci/deploy/devsite.sh
    branches: master
    timeout_in_minutes: 30
    agents:
      queue: builder
    concurrency: 1
    concurrency_group: deploy/devsite

  # TODO(benesch): the next two scripts should be unified, and run in
  # ci-builder.
  - command: ci/deploy/docker.sh
    timeout_in_minutes: 10
    concurrency: 1
    concurrency_group: deploy/docker
  - command: ci/deploy/deb.sh
    branches: master
    timeout_in_minutes: 10
    concurrency: 1
    concurrency_group: deploy/deb

  - command: ci/deploy/macos.sh
    agents:
      queue: mac
    timeout_in_minutes: 30
    concurrency: 1
    concurrency_group: deploy/macos
