[package]
name = "symbiosis"
description = "Built-in OLTP support via symbiosis."
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
dataflow-types = { path = "../dataflow-types" }
expr = { path = "../expr" }
failure = "0.1.8"
log = "0.4.8"
ore = { path = "../ore" }
pgrepr = { path = "../pgrepr" }
tokio = "0.2"
tokio-postgres = { version = "0.5.4", features = ["with-chrono-0_4", "with-serde_json-1"] }
repr = { path = "../repr" }
serde_json = "1.0"
sql = { path = "../sql" }
sql-parser = { path = "../sql-parser" }
whoami = "0.8"
