# This is a dummy crate that serves to enable features of dependencies on
# non-macOS platforms. It is only depended upon on non-macOS platforms, so the
# features it enables are only enabled on non-macOS platforms. If Cargo learns
# to natively support target-specific features [0], this crate can be removed.
#
# [0]: https://github.com/rust-lang/cargo/issues/1197

[package]
name = "materialized-not-macos"
description = "Hack for target-specific Cargo features with stable Rust."
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "dummy.rs"

[dependencies]
prof = { path = "../../prof", features = ["jemalloc"] }
