[package]
name = "metastore"
description = "Storage of persistent, distributed metadata."
version = "0.1.0"
authors = ["Nikhil Benesch <nikhil.benesch@gmail.com>"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
bincode = "1.1.2"
failure = "0.1.5"
futures = "0.1"
lazy_static = "1.3.0"
linked-hash-map = "0.5.2"
log = "0.4"
ore = { path = "../ore" }
serde = { version = "1.0.89", features = ["derive"] }
slog = "2.4.1"
slog-stdlog = "3.0.2"
tokio = "0.1.16"
tokio-zookeeper = { git = "https://github.com/jonhoo/tokio-zookeeper.git" }
