[package]
name = "metrics"
description = "Run metrics on chbench."
version = "0.1.0"
edition = "2018"
publish = false

[[bin]]
name = "metrics"
path = "bin/metrics.rs"

[dependencies]
regex = "1.3.1"
prometheus = { version = "0.7", features = ["push", "process"] }
chrono = "0.4.9"
postgres = { version = "0.16.0-rc.2", features = ["with-chrono-0_4"] }
time = "*"
