[package]
name = "metrics"
description = "Run metrics on chbench."
version = "0.1.0"
edition = "2018"
publish = false

[[bin]]
name = "metrics"
path = "bin/metrics.rs"

[dependencies]
regex = "1.3.1"
prometheus = { version = "0.7", features = ["push"] }
chrono = "0.4.9"
