[package]
name = "dataflow-bin"
description = "Utility binaries for the dataflow crate."
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
ore = { path = "../ore" }
structopt = "0.3.25"
timely = { git = "https://github.com/TimelyDataflow/timely-dataflow", default-features = false, features = ["bincode"] }
