[package]
name = "ccsr"
description = "Confluent-compatible schema registry API client."
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
failure = "0.1"
reqwest = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.40"

[dev-dependencies]
hyper = "0.12"
lazy_static = "1.3"
tokio = "0.1"
